name: sync
on:
  push:
    branches: 'main'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Chekout remote repo
        uses: actions/checkout@v4
        with:
          repository: NorDevLab/nordevlab.github.io
          ref: 'main'
          token:  ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          path: repo-site
      
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          path: repo-site-current

  #    - run: sed -i 's,https://unpkg.com/@teleporthq/teleport-custom-scripts,./ndlb.js,g' public/index.html
   #     working-directory: ./repo-site-current
        
      - name: build app
        working-directory: ./repo-site-current
        run: npm i && npm run build
        
        

      
      - name: Copy
        run: |
          cp -r repo-site-current/build/* repo-site/ && \
          cd repo-site && \
          git config user.name "GitHub Actions Bot" && \
          git config user.email "foo@bar.com"
      
      - name: Push
        run: cd repo-site && git add . && git commit -am 'sync' && git push origin main --force
      
